baseurl: "http://192.168.1.15/"
title: Rayguo17's Blog
theme: hugo-PaperMod-master

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
hasCJKLanguage: true 
languageCode: "zh-cn"
languages:
  en:
    languageName: "Chinese"
    #weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives/
          weight: 5
        - name: Tags
          url: tags/
          weight: 10
        - name: Search
          url: search/
  
outputs:
  home:
    - HTML
    - RSS
    - JSON

params: 
  description: "This is rayguo17's personal blog! Being part of the service hosts on raspberry pi. Here i will share my study notes, daily notes. Content will mainly be in Chinese, but i am improving my english, so hopes to have more english contents soon! Enjoy!"
  author: Rayguo17
  DateFormat: "January 2, 2006"
  ShowPostNavLinks: true
  ShowBreadCrumbs: true

  disableScrollToTop: false
  ShowShareButtons: true
  ShowReadingTime: true
  ShowWordCount: true
  defaultTheme: auto
  ShowCodeCopyButtons: true
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  assets:
    favicon: "img/favicon.ico"
    favicon16x16: "img/favicon-16x16.png"
    favicon32x32: "img/favicon-32x32.png"
    apple_touch_icon: "img/apple-touch-icon.png"

  label:
    text: "Home"
    icon: "img/apple-touch-icon.png"
    iconHeight: 35

  homeInfoParams:
    Title: á€™á€„á€ºá€¹á€‚á€œá€¬á€•á€« ğŸ™
    Content: >
            æˆ‘æ˜¯Rayguo17ï¼Œç¼…ç”¸ğŸ‡²ğŸ‡²ç”Ÿäººï¼Œä»å°åœ¨ä¸­å›½ğŸ‡¨ğŸ‡³é•¿å¤§ã€‚ç›®å‰æ˜¯SJTU_ISçš„å¤§å››å­¦ç”Ÿï¼Œå–œæ¬¢æŠ˜è…¾ä¸€äº›å¥‡å¥‡æ€ªæ€ªçš„ä¸œè¥¿ï¼Œæ—¶ä¸æ—¶ä¼šå†™æˆåšå®¢è®°å½•ä¸‹æ¥ã€‚ç›®æ ‡æ˜¯ä¸ºè‡ªå·±è€Œæ´»ï¼Œå› ä¸ºè‡ªå·±çš„æ„æ„¿è€Œå»åšä¸€äº›äº‹æƒ…ã€‚ç›®å‰æƒ³åˆ°çš„å°±æ˜¯åšå¿—æ„¿è€…ï¼Œåšè‡ªå·±æƒ³åšçš„ç ”ç©¶ï¼Œè®¤è¯†å¤šç‚¹äººï¼Œæ¥æ”¶ä¸åŒçš„ä»·å€¼è§‚ã€‚æ½œæ„è¯†é‡Œç»å¸¸æŠ—æ‹’æ”¹å˜ï¼Œä½†æ˜¯ï¼ŒLife is too short to worry About. è¡ŒåŠ¨å§ï¼Œéªšå¹´ï¼
            
  
  SocialIcons:
    - name: "twitter"
      url: "https://twitter.com/rayguo17"
    - name: "github"
      url: "https://github.com/rayguo17"

  profileMode:
    enabled: false

  cover:
    hidden: true 
  
  editPost:
    URL: "https://github.com/rayguo17/Blog/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
